// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL3lPg5UTTKQLk_IRiHqYJ9fuJ0Y1qB3k',
    appId: '1:208851008762:web:9926eac30378c9233e9d43',
    messagingSenderId: '208851008762',
    projectId: 'ecomapp-47721',
    authDomain: 'ecomapp-47721.firebaseapp.com',
    storageBucket: 'ecomapp-47721.firebasestorage.app',
    measurementId: 'G-G54DWS5CHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfQsZ5ZbXKECuY1Urw2I8GnA4revIMjYQ',
    appId: '1:208851008762:android:5322def14186b32e3e9d43',
    messagingSenderId: '208851008762',
    projectId: 'ecomapp-47721',
    storageBucket: 'ecomapp-47721.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBulhdAh9MWcubbtILkKuX8GBLmshOuViU',
    appId: '1:208851008762:ios:08b01ec69c49b7d03e9d43',
    messagingSenderId: '208851008762',
    projectId: 'ecomapp-47721',
    storageBucket: 'ecomapp-47721.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBulhdAh9MWcubbtILkKuX8GBLmshOuViU',
    appId: '1:208851008762:ios:08b01ec69c49b7d03e9d43',
    messagingSenderId: '208851008762',
    projectId: 'ecomapp-47721',
    storageBucket: 'ecomapp-47721.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL3lPg5UTTKQLk_IRiHqYJ9fuJ0Y1qB3k',
    appId: '1:208851008762:web:aff63ded42eebd423e9d43',
    messagingSenderId: '208851008762',
    projectId: 'ecomapp-47721',
    authDomain: 'ecomapp-47721.firebaseapp.com',
    storageBucket: 'ecomapp-47721.firebasestorage.app',
    measurementId: 'G-42LJB7TYPH',
  );
}
